api:
  id: "65551"
  
env.port: "${https.private.port}"
  
caqh:
 sftp:
   host: "sftp.proview.caqh.org"
   user: "![oQOtzYYubt/4ejgpHerS3g==]"
   password: "![zaykkqapvo1H9D7esyNkKQ==]"
   directory: "/Outgoing"
   
pnmSapi:
  host: "vems-mule-sfpnm-sapi-uat.usg-w1.gov.cloudhub.io"
  port: "443"
  url:  "/api/v1"
  methods:
     care:                          "/care-provider-adverse-action"
     content-version:               "/content-version"
     contentDocument-link:          "/content-document-link"
     get-content-version:          "/content-version/{id}"
     
app:
  careProviderAdverseAction:
    pipe-delimited-filename: "Sanctions_Extracts/Sample_Sanction_Extracts_V2"
  sapi:
    credentials:
      client_id: "![r/ISqTuPMde71DSpmXE5+jemplJ8WamqqXVj1ml0ru+4x4rg9gqVfQ==]"
      client_secret: "![6zQuCPSRVype13dycEjVlj2RxPLn90nCC8NbTGljML46dWMCw8uC/g==]"