api:
  id: "64987"
  
caqh:
 sftp:
   host: "sftp.proview.caqh.org"
   #host: "sftp-demo.nonprod.caqh.org"
   user: "![/3ZeyBEJaW7TFcRB6KR03g==]"
   #user: "![bJpd2vE+1d5PdlSR4D8CWg==]" 
   password: "![va6Bo2PTX9SPt1yapxy9fA==]"
   #password: "![/rAReTkf8pOsXwRadUPtrA==]"
   directory: "/Outgoing"
   
pnmSapi:
  host: "vems-mule-sfpnm-sapi-dev.usg-w1.gov.cloudhub.io"
  port: "443"
  url:  "/api/v1"
  methods:
     care:                          "/care-provider-adverse-action"
     content-version:               "/content-version"
     contentDocument-link:          "/content-document-link"
     get-content-version:          "/content-version/{id}"
     
app:
  careProviderAdverseAction:
    #pipe-delimited-filename: "Maximus_Sanctions_Extarcts/CustomSanction_ACS1708XX_20231205_091427.zip"
    #pipe-delimited-filename: "Sanctions_Extarcts/CustomSanction_ACS1708XX_20231205_091427.zip"
    pipe-delimited-filename: "/SanctionExtract.txt"
    
    

  sapi:
    credentials:
      clientId: "![R4JlXwbQDn1tNeuUB9t/y9YYyRdKOikOoxTyyRVOFRT1MzLu0rfp6g==]"
      clientSecret: "![rR5HLA+StUW2H7ZAsyS26M5pY2JOX4pMRVifWfunsd7qxgZagcWtLg==]"
  