api:
  id: "64988"

#caqh:
# sftp:
#   host: "sftp-demo.nonprod.caqh.org"
#   user: "![bJpd2vE+1d5PdlSR4D8CWg==]" 
#   password: "![/rAReTkf8pOsXwRadUPtrA==]"
#   directory: "Incoming/"


caqh:
 sftp:
   host: "sftp.proview.caqh.org"
   user: "![/3ZeyBEJaW7TFcRB6KR03g==]"
   password: "![va6Bo2PTX9SPt1yapxy9fA==]"
   directory: "/Outgoing"
   
pnmSapi:
  host: "vems-mule-sfpnm-sapi-qa.usg-w1.gov.cloudhub.io"
  port: "443"
  url:  "/api/v1"
  methods:
     care:                          "/care-provider-adverse-action"
     content-version:               "/content-version"
     contentDocument-link:          "/content-document-link"
     get-content-version:          "/content-version/{id}"
     
app:
  careProviderAdverseAction:
    pipe-delimited-filename: "Sanctions_Extracts/Sample_Sanction_Extracts_V2"
    
    

  sapi:
    credentials:
      clientId: "![R4JlXwbQDn1tNeuUB9t/y9YYyRdKOikOoxTyyRVOFRT1MzLu0rfp6g==]"
      clientSecret: "![rR5HLA+StUW2H7ZAsyS26M5pY2JOX4pMRVifWfunsd7qxgZagcWtLg==]"
  